### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by berijan** [Hernrup/homeassistant-svc2evnt#5]
Hi.

Since last version of HA I'm getting this error, is this something that will be will fix in near future?

#ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'svc2evnt'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'svc2evnt'#

**Comment by paulius2k** [comment]
That's exactly what happened after I updated to `core-2021.6.0`:
```
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 22:41:31 (1 occurrences)
Last logged: 22:41:31

Setup failed for svc2evnt: Integration not found.
```

@Hernrup - could we expect an update to the manifest file?  Thank you!

**Comment by paulius2k** [comment]
I fixed it temporarily by adding a `"version": "0.0.1",` to a `/config/custom_components/svc2evnt/manifest.json` file and restarting HASS.

**Comment by Hernrup** [comment]
Hi all, sorry for the inactivity. 
This repo was not rely on my monitored list since its such a small component and there is rely no plan for additional developments. 

I'll try to get this fixed soon.

If anyone would like a maintainer role and make additional improvements to it you are welcome.

**Comment by Hernrup** [comment]
This is now fixed as of https://github.com/Hernrup/homeassistant-svc2evnt/pull/6/commits/2c45503e35dd67a64189e23857c1ea72f5af6a92

I was a bit of a hassle to get the build system to update to version number but now its working. Thanks for the report @berijan

**Comment by berijan** [comment]
Thank you for your effort.

Jan 

Den 17 juli 2021 14:07, kI 14:07, Mikael Hernrup ***@***.***> skrev:
